# Generated by Django 3.2.2 on 2021-05-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='is_used'),
        ),
    ]
