# Generated by Django 3.2.2 on 2021-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverifyrecord_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_validation_email',
            field=models.BooleanField(default=False, verbose_name='is_validation_email'),
        ),
    ]
