# Generated by Django 3.2.2 on 2021-05-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKPostcodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='postcode')),
                ('county', models.CharField(db_index=True, max_length=50, null=True, verbose_name='county')),
                ('district', models.CharField(db_index=True, max_length=50, null=True, verbose_name='district')),
                ('country', models.CharField(max_length=20, null=True, verbose_name='country')),
                ('postcode_area', models.CharField(max_length=8, verbose_name='postcode_area')),
                ('postcode_district', models.CharField(max_length=8, verbose_name='postcode_district')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=14, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=14, verbose_name='longitude')),
                ('easting', models.DecimalField(blank=True, decimal_places=0, max_digits=14, verbose_name='easting')),
                ('north', models.DecimalField(blank=True, decimal_places=0, max_digits=14, verbose_name='north')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_uk_postcode', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'uk_postcode',
                'db_table': 'uk_postcode',
                'ordering': ['postcode', 'county'],
                'unique_together': {('postcode',)},
            },
        ),
    ]
